{{- $ingressHost := include "ingressHost" . -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.global.env }}-{{ $.Chart.Name }}
  labels:
    app.kubernetes.io/name: {{ $.Chart.Name }}
    helm.sh/chart: {{ $.Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/ingress.allow-http: "false"
    nginx.ingress.kubernetes.io/whitelist-source-range: 10.0.0.0/8,192.168.0.0/16,172.16.0.0/12
    nginx.ingress.kubernetes.io/proxy-body-size: 64m
    # Because prod is on .dm.gg and not .kube.dm.gg, the dns entry is already created
    {{- if not (eq .Values.global.env "prod") }}
    external-dns.alpha.kubernetes.io/hostname: {{ .Chart.Name }}{{ $ingressHost }}
    external-dns.alpha.kubernetes.io/target: {{ include "ingressHostTarget" . }}
    external-dns.alpha.kubernetes.io/ttl: "120"
    {{- end }}
spec:
  rules:
  - host: {{ .Chart.Name }}{{ $ingressHost }}
    http:
      paths:
      - backend:
          service:
            name: {{ $.Chart.Name }}
            port:
              number: 80
        path: /
        pathType: ImplementationSpecific
  tls:
  - hosts:
    - {{ .Chart.Name }}{{ $ingressHost }}
    secretName: {{ .Chart.Name }}{{ $ingressHost | replace "." "-" }}-tls
